name = "tatoeba"
version = "0.1.0-rc.1"

licences = ["Apache-2.0"]

description = "A complete, documented API wrapper for the Tatoeba corpus, built in Gleam."
repository = { type = "github", user = "vxern", repo = "tatoeba" }
links = [{ title = "Website", href = "https://vxern.dev" }]

target = "erlang"
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
